[package]
name = 'oracle'
version = '0.0.1'


[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'


[addresses]
AptosFramework="0x1"
oracle="0x867b30a905a6e0802db6bdc8b61d7b0dcad755a408b73999c9cf44a6645a1ede"